app:
  name: IntelliiGuru
  version: 1.0
  owner: Balkrishna
  userid: 55438

  security:
    jwt:
      secret: mySecret
      expiry: "3600"

spring:
  datasource:
    url: root@127.0.0.1:3306/krishnaresource
    username: root
    password: Krishna@1977
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
