server:
  port=8080

file:
  upload-dir: uploads










































spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/krishnaresource
    username: root
    password: Krishna@1977
    driver-class-name: com.mysql.cj.jdbc.Driver
